[package]
name = "stackedconfig"
version = "0.1.0"
authors = ["Aaron Stevens <bheklilr2@gmail.com>"]
description = "Treat multiple nested config objects as a single config object with precedence."
license = "MIT"

[dependencies]
serde_json = "1.0"
